### ISSUE TITLE
Error loading in GToolkit v0.5.1 image (NeoJSON conflict)

### ISSUE THREAD

**Issue by lukego** [feenkcom/gt4p3#1]
I tried loading this package in GToolkit v0.5.1 on my Mac and got this error that I don't know how to resolve:

<img width="943" alt="screenshot 2019-02-15 at 07 19 01" src="https://user-images.githubusercontent.com/13791/52838266-581c9d80-30f2-11e9-87d6-f5871f3fff37.png">

**Comment by girba** [comment]
Can you check in the latest GT version?

**Comment by chisandrei** [comment]
You get this problem in Metacello when there is a version of a project in the image and you try to load a different version using a different configuration or baseline. To fix it you can specify using `onConflict:` what   should happen in this case. For example below when a conflict is detected the version that is being loaded takes precedence. 

```
Metacello new
	baseline: '<baseline>';
	repository: '<repo>';
	onConflict: [ :err | err useIncoming ];
        load
```

There is also `useLoaded` to not load the new version and keep the current one.

**Comment by girba** [comment]
It works in the latest GT.
